<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php include ("../style/style.css");?>
<?php include("../include/entete.php");?>
<body>

<strong>Mentions légales du site.</strong><br>
Polyclinique des Alpes du Sud Société anonyme au capital de 2 193 325, 50 Euros Immatriculée au RCS de Gap sous le n° 424 809 317.
<strong>Téléphone :</strong> 0 826 555 001<br>
<strong>Directeur de la Publication :</strong> Christian BOYER (PDG).<br>
<strong>Conception et réalisation du site :</strong> Peter LAMPSON.<br>
<strong>Créations images 3D et plan d’accès :</strong> France Impression Gap.<br>
<strong>Crédits photographiques :</strong> François CELCE.<br>
<strong>Correspondant CNIL :</strong> Pascal LAMPSON.<br>

Le présent site Internet est réalisé bénévolement. Soucieux du respect de votre vie privée, la Polyclinique des Alpes du Sud s’engage à ce que la collecte et le traitement d’informations personnelles, effectués au sein du présent site, soient effectués conformément à la loi n°78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés dite loi «Informatique et Libertés». Par données personnelles, la Polyclinique des Alpes du Sud entend toutes les informations relatives à une personne physique identifiée ou identifiable par un ou plusieurs éléments qui lui sont propres fournies sur notre site Internet afin notamment de nous contacter ou d’obtenir des informations sur notre activité. Les informations ainsi fournies sur notre site sont exclusivement destinées à permettre le traitement de vos demandes.
 – Vous disposez d’un droit d’opposition au traitement par la Polyclinique des Alpes du Sud des données personnelles vous concernant, ainsi que du droit de vous opposer, sans frais, à ce que vos données personnelles soient utilisées à des fins de prospection par la Polyclinique des Alpes du Sud.
 – Vous disposez d’un droit d’accès, de communication, de modification, de rectification et de suppression des informations vous concernant, et recueillies lors de vos visites du site Internet de la Polyclinique des Alpes du Sud.
 – Vous disposez du droit d’interroger la Polyclinique des Alpes du Sud en vue d’obtenir la confirmation que vos données personnelles font ou ne font pas l’objet d’un traitement, des informations relatives aux finalités du traitement, aux catégories de destinataires auxquelles celles-ci sont communiquées. Nous vous indiquons qu’une copie des données à caractère personnel vous concernant peut vous être délivrée, à votre demande et contre remboursement des coûts de reproduction de celle-ci. Toutefois, la Polyclinique des Alpes du Sud a la possibilité de s’opposer aux demandes manifestement abusives, notamment par leur nombre, leur caractère répétitif ou systématique. Pour exercer ces droits, il suffit d’adresser un courrier postal à l’adresse suivante : Polyclinique des Alpes du Sud, à l’attention du Dr.Christian BOYER, 3-5 rue Antonin Coronat 05000 Gap.
 – Les informations personnelles recueillies dans le cadre du service sont conservées conformément aux règles prescrites par la loi « Informatique et Libertés », et pendant une durée justifiée par la finalité de leur traitement.
 – Afin de faciliter votre accès aux services proposés (notamment, en limitant le temps de chargement de nos pages lors de vos futures visites), nous pouvons implanter des cookies, c’est-à-dire des fichiers de petite taille, sur votre disque dur. Ces cookies sont uniquement destinés à constituer des témoins de connexions, et donc d’identifier votre ordinateur pour faciliter votre navigation. Vous pouvez vous opposer à l’installation de cookies en configurant votre navigateur, étant entendu qu’une telle opposition est susceptible d’altérer la qualité de votre accès et de votre navigation.
 – La structure générale du site de la Polyclinique des Alpes du Sud et l’ensemble des contenus diffusés sur ce site (images, articles, photographies, logos, marques, vidéos, interviews, sons, textes…), sont protégés par la législation en vigueur en France en matière de propriété intellectuelle, et notamment le droit d’auteur, le droit à l’image. Tous les droits de reproduction sont réservés, y compris pour les textes, les documents téléchargeables, les représentations iconographiques et photographiques. A ce titre, à défaut d’autorisation de la Polyclinique des Alpes du Sud, il est strictement interdit d’exploiter les contenus du site et notamment de les reproduire, représenter, modifier ou adapter en tout ou partie.
 – La Charte de la Personne Hospitalisée établie en liaison avec la Fédération Intersyndicale des Etablissements d’Hospitalisation Privée est téléchargeable.
 – Le site de la Polyclinique des Alpes du Sud revêt un caractère strictement informatif. Il n’emporte aucun engagement juridique ni accord contractuel de la part de la Polyclinique des Alpes du Sud qui se réserve par ailleurs de modifier, à sa convenance, les caractéristiques des informations et services proposés au sein de l’établissement. La Polyclinique des Alpes du Sud met tout en œuvre pour offrir aux internautes des informations fiables sur les activités (en termes de spécialités et de consultations notamment), les conditions de séjour et la structure médicale en place. Toutefois, la Polyclinique des Alpes du Sud ne saurait garantir aux internautes l’exactitude, la complétude, l’actualisation en temps réel des informations fournies.
 – La Polyclinique des Alpes du Sud ne saurait garantir à l’utilisateur le secret de la correspondance des courriers électroniques ou de tout autre mode de communication utilisant le support du réseau internet et pouvant être captés par un tiers, du fait du mode de circulation des données sur ce réseau. De plus, il appartient à chaque utilisateur de prendre toutes les mesures appropriées de façon à protéger ses propres données et /ou logiciels de la contamination d’éventuels virus circulant sur internet. En conséquence, la responsabilité de la Polyclinique des Alpes du Sud ne pourra en aucun cas être engagée du fait de l’utilisation des informations fournies et /ou des outils mis à disposition sur ce site. La responsabilité de la Polyclinique des Alpes du Sud ne saurait être engagée en cas de difficultés de fonctionnement ou interruption de ses services indépendamment de la volonté de la Polyclinique des Alpes du Sud, l’interruptions momentanées du site de l’établissement nécessaires à leur évolution, maintenance ou mise à jour. Les défaillances ou dysfonctionnement du réseau Internet dans la transmission de données, messages ou documents.
 – La création de liens hypertextes vers le site Polyclinique des Alpes du Sud est soumise à l’accord préalable du Président Directeur Général de la Polyclinique des Alpes du Sud.
 – Les liens hypertextes mis en œuvre en direction d’autres sites ne sauraient engager la responsabilité de la Polyclinique des Alpes du Sud, celui-ci n’exerçant aucun contrôle sur le contenu de ces sites.
</div>
</body>
</html>