<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php include ("../style/style.css");?>
<?php include("../include/entete.php");?>
<body>
<div id="divleft"></div><div id="divright">
</div>
<div id="divmiddle">
<p style="text-align: justify;">Au début des années 1930, si l’hôpital de Gap avait embauché <strong>Antonin Coronat</strong> comme chirurgien, la Clinique des Alpes n’aurait peut-être pas vu le jour si vite. Mais le maire de l’époque, Auguste MURET choisit le docteur Bruyère pour l’hôpital et Louis Coronat décida alors de construire son propre établissement. Ainsi vit le jour la <strong>Clinique des Alpes</strong> à l’automne 1932. Un outil doté d’un équipement de dernière génération, d’une installation des plus modernes pour la ville de Gap et le département des Hautes-Alpes. Antonin Coronat (qui se distinguera par la suite par son soutien à la résistance) s’y installe et exerce dans les meilleures conditions la chirurgie. Il travaille avec des religieuses infirmières dans un cadre très familial. Les sœurs s’occupent de la Clinique comme d’une grande maison, gérant les soins mais aussi l’intendance ou l’administratif.</p>
<p style="text-align: justify;">Il faudra attendre les années 1960 pour voir arriver un personnel diplômé non religieux. A cette époque la Clinique possède son propre potager pour la cuisine, son tilleul pour la tisane, ses arbres fruitiers pour les desserts. Le linge est bouilli sur place. Chaque chambre a son crucifix et ses médailles, la chapelle permet les baptêmes sur place des la naissance. Avec le départ progressif des sœurs, les signes religieux sont supprimés des chambres. L’ambiance reste chaleureuse de part la présence du docteur Coronat, rejoint à la fin des années 1960 par son fils Louis, qui a fait de brillante études de chirurgie à Lyon. Le bâtiment est agrandi afin d’augmenter sa capacité, des nouvelles salles complètent le bloc opératoire. La Clinique des Alpes est un établissement MCO, on y pratique la chirurgie (générale et oto-rhino-laryngologique), la médecine (cardiologie, pneumologie et gastro-entérologie), et l’obstétrique avec un service spécifique de maternité. Les bébés apportent de la vie et des cris jusqu’en 1995, date de sa fermeture.</p>
<p style="text-align: center;"><img title="La Polyclinique des Alpes du Sud." src="../image/historique_polyclinique_gap.jpg" alt="" width="780" height="155" /></p>
<p style="text-align: justify;">Progressivement la Clinique des Alpes s’adapte aux changements et aux normes. C’est ainsi qu’elle embauche du personnel. Au tout début des années 90, l’équipe est renforcée par l’arrivée d’un ophtalmologiste, d’un orthopédiste et d’un troisième anesthésiste. Parallèlement le bâtiment est agrandi permettant de rénover une partie des chambres d’hospitalisation. Le mouvement va s’accélérer autour de l’an 2000 avec l’arrivée d’une équipe d’urologie, de deux autres ophtalmologistes et deux orthopédistes. Le docteur Louis Coronat n’ayant pas de successeur, va vendre l’établissement aux praticiens qui y exercent et c’est ainsi que naîtra en Janvier 2000, <strong>LA POLYCLINIQUE DES ALPES DU SUD</strong> (PAS). Auparavant, il aura lancé la rénovation du bloc opératoire pour en faire un outil qui permette de réaliser des actes chirurgicaux plus spécialisés en toute sécurité.</p>
<p style="text-align: justify;">La nouvelle équipe qui prend en main la gestion de l’établissement début 2000 comporte un directeur qui officie sous la responsabilité du PDG, le docteur <strong>Jean-Loup CARTIER</strong>. De nombreux chantiers attendent cette équipe : la négociation des 35 heures qui est menée avec sucées, puis celle de la nouvelle convention collective. Parallèlement il faut moderniser les équipements, acquérir du matériel adapté aux exigences de sécurité et faire face à la crise du secteur des cliniques privées qui aboutira à la fermeture de nombreux établissements sur tout le territoire. A cette époque, la Polyclinique bénéficiera du soutien de l’ensemble des décideurs locaux ce qui lui permettra de passer sans encombre ces épreuves. Mais le bâtiment vieillit. Les chambres ne sont plus aux normes, trop petites, sans douche individuelles. Le circuit de chauffage, le circuit d’eau, l’isolation, l’installation électrique deviennent obsolètes. Il faudrait entièrement rénover le bâtiment, ce qui n’est pas anodin. Comme il est impossible de fermer complètement les différents services pendant plusieurs mois, se dessine un projet d’association avec des lits de Rhône-Azur. La solution devient alors évidente de construire une structure de soins neuve à la périphérie de Gap. En 2003, la venue de M. Matteï, alors ministre de la santé apportera un soutien de taille au projet.</p>
<p style="text-align: justify;">Cinq années plus tard, la nouvelle polyclinique voyait le jour sur le site de Charance offrant aux Hauts-Alpins un équipement de grande qualité prêt à répondre aux défis de santé publique des prochaines années. La Polyclinique des Alpes du Sud garde de sa glorieuse aînée la conviction que le patient doit être toujours placé au coeur de ses préoccupations. C'est ainsi que le personnel et les médecins cherchent toujours à privilégier une relation avec les patients fondée sur le respect et la proximité.</p>
Cette volonté d'aller de l'avant et de sans cesse s'améliorer reste des valeurs clé de la <strong>Polyclinique des Alpes du Sud</strong> qui saura ainsi faire évoluer au fil du temps son offre de soins en fonction des besoins futurs.

<span style="color: #ffffff;">.</span>

&nbsp;
<p style="text-align: center;"><img  style="border: 1px solid black;" title="Polyclinique des Alpes du Sud." src="../image/03.jpg" alt="" width="800" height="362" /></p>
</div>
<?php include("../include/pied.php");?>
</body>
</html>